export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const EDIT_SUBCATEGORY = 'EDIT_SUBCATEGORY';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
export const LOAD_SUBCATEGORIES = 'LOAD_SUBCATEGORIES';
