export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const ADD_DELETED_ACCOUNT = 'ADD_DELETED_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';
export const REMOVE_DELETED_ACCOUNT = 'REMOVE_DELETED_ACCOUNT';
export const RESET_DELETED_ACCOUNTS = 'RESET_DELETED_ACCOUNTS';
