export const ADD_TRANS_FILTER = 'ADD_TRANS_FILTER';
export const REMOVE_TRANS_FILTER = 'REMOVE_TRANS_FILTER';
export const RESET_TRANS_FILTERS = 'RESET_TRANS_FILTERS';
export const SET_BUDGET_INFO = 'SET_BUDGET_INFO';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_EDITING_TRANSACTION = 'SET_EDITING_TRANSACTION';
export const SET_SHOW_SIDEBAR = 'SET_SHOW_SIDEBAR';
export const SET_TOP_EXPENSES = 'SET_TOP_EXPENSES';
