import { FirebaseCategory } from '../firebase/types';

export const createInitialCategory = (category: FirebaseCategory, userId: string): FirebaseCategory => ({
  ...category,
  userId,
})

export const defaultCategories: FirebaseCategory[] = [
  {
    budgetPercent: 15,
    budgets: [],
    name: 'Housing',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 12,
    budgets: [],
    name: 'Auto & Transportation',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 14,
    budgets: [],
    name: 'Food',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 8,
    budgets: [],
    name: 'Utilities',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 6,
    budgets: [],
    name: 'Medical',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 4,
    budgets: [],
    name: 'Shopping',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 4,
    budgets: [],
    name: 'Insurance',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 1,
    budgets: [],
    name: 'Household Supplies',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 2,
    budgets: [],
    name: 'Personal',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 10,
    budgets: [],
    name: 'Debt',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 5,
    budgets: [],
    name: 'Retirement',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 1,
    budgets: [],
    name: 'Education',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 4,
    budgets: [],
    name: 'Gifts & Donations',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 5,
    budgets: [],
    name: 'Entertainment',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 4,
    budgets: [],
    name: 'Travel',
    subcategories: [],  
    userId: '',
  },
  {
    budgetPercent: 5,
    budgets: [],
    name: 'Savings',
    subcategories: [],  
    userId: '',
  },
]